"""initial schema from existing tables

Revision ID: 9b73f8e3f277
Revises: 
Create Date: 2026-02-23 04:03:47.427746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b73f8e3f277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_sessions', 'filter_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('monitored_products', 'platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'hepsiburada'::character varying"))
    op.drop_index(op.f('ix_monitored_products_sku'), table_name='monitored_products')
    op.create_index(op.f('ix_monitored_products_sku'), 'monitored_products', ['sku'], unique=False)
    op.create_index(op.f('ix_monitored_products_brand'), 'monitored_products', ['brand'], unique=False)
    op.create_index(op.f('ix_monitored_products_platform'), 'monitored_products', ['platform'], unique=False)
    op.create_index('ix_monitored_products_platform_active', 'monitored_products', ['platform', 'is_active'], unique=False)
    op.alter_column('price_monitor_tasks', 'last_inactive_skus',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index(op.f('idx_product_sellers_product_id'), table_name='product_sellers')
    op.alter_column('product_snapshots', 'coupons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('product_snapshots', 'campaigns',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('seller_snapshots', 'campaigns',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index('ix_seller_snapshots_product_merchant_date', 'seller_snapshots', ['monitored_product_id', 'merchant_id', 'snapshot_date'], unique=False)
    op.drop_index(op.f('idx_sponsored_brand_ads_task'), table_name='sponsored_brand_ads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sponsored_brand_ads_task'), 'sponsored_brand_ads', ['search_task_id'], unique=False)
    op.drop_index('ix_seller_snapshots_product_merchant_date', table_name='seller_snapshots')
    op.alter_column('seller_snapshots', 'campaigns',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('product_snapshots', 'campaigns',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('product_snapshots', 'coupons',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_product_sellers_product_id'), 'product_sellers', ['product_id'], unique=False)
    op.create_index(op.f('idx_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.alter_column('price_monitor_tasks', 'last_inactive_skus',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_monitored_products_platform_active', table_name='monitored_products')
    op.drop_index(op.f('ix_monitored_products_platform'), table_name='monitored_products')
    op.drop_index(op.f('ix_monitored_products_brand'), table_name='monitored_products')
    op.drop_index(op.f('ix_monitored_products_sku'), table_name='monitored_products')
    op.create_index(op.f('ix_monitored_products_sku'), 'monitored_products', ['sku'], unique=True)
    op.alter_column('monitored_products', 'platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'hepsiburada'::character varying"))
    op.alter_column('category_sessions', 'filter_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
